# Generated by Django 6.1.1 on 2026-09-23 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaitem',
            name='media_type',
        ),
    ]
