# Generated by Django 6.1.1 on 2026-09-24 21:56

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_gallery', '0002_remove_mediaitem_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='audio',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/'),
        ),
    ]
